### ISSUE TITLE
NumPy 2.0.0 breaking changes 

### ISSUE THREAD

**Issue by zebbecker** [Earth-Information-System/fireatlas#68]
When running v3 with NumPy 2.0.0 installed (this came up when I re-created my environment on the new MAAP version yesterday), `postprocess.save_large_fires_layers` throws a new error. 

The error message points to NumPy 2.0.0 the migration guide with info on how to fix this [here](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword). 

To reproduce, checkout [this branch](https://github.com/Earth-Information-System/fireatlas/tree/zb/fireforward-compare) and run `pytest --runslow`. 

Trace: 

```
fireatlas/utils.py:14: in wrap
    result = f(*args, **kwargs)
fireatlas/postprocess.py:396: in save_large_fires_layers
    data = merge_rows(data, fid)
fireatlas/postprocess.py:364: in merge_rows
    output["flinelen"] = output.fline.apply(lambda x: 0 if x is None else x.length) / 1e3  # km
../../fireatlas/v3env/lib/python3.11/site-packages/geopandas/geoseries.py:660: in apply
    result = super().apply(func, args=args, **kwargs)
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/series.py:4924: in apply
    ).apply()
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/apply.py:1427: in apply
    return self.apply_standard()
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/apply.py:1507: in apply_standard
    mapped = obj._map_values(
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/base.py:919: in _map_values
    return arr.map(mapper, na_action=na_action)
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/arrays/base.py:2322: in map
    return map_array(self, mapper, na_action=na_action)
../../fireatlas/v3env/lib/python3.11/site-packages/pandas/core/algorithms.py:1741: in map_array
    values = arr.astype(object, copy=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <GeometryArray>
[<LINESTRING (-1694328.142 -671360.897, -1694129.488 -671023.42, -1693936.139...>,
 <MULTILINESTRING (...00...>,
 <MULTILINESTRING ((-1690125.683 -631707.974, -1690064.154 -631601.204, -1690...>]
Length: 124, dtype: geometry
dtype = <class 'object'>, copy = False

    def astype(self, dtype, copy=True):
        """
        Cast to a NumPy array with 'dtype'.
    
        Parameters
        ----------
        dtype : str or dtype
            Typecode or data-type to which the array is cast.
        copy : bool, default True
            Whether to copy the data, even if not necessary. If False,
            a copy is made only if the old dtype does not match the
            new dtype.
    
        Returns
        -------
        array : ndarray
            NumPy ndarray with 'dtype' for its dtype.
        """
        if isinstance(dtype, GeometryDtype):
            if copy:
                return self.copy()
            else:
                return self
        elif pd.api.types.is_string_dtype(dtype) and not pd.api.types.is_object_dtype(
            dtype
        ):
            string_values = to_wkt(self)
            pd_dtype = pd.api.types.pandas_dtype(dtype)
            if isinstance(pd_dtype, pd.StringDtype):
                # ensure to return a pandas string array instead of numpy array
                return pd.array(string_values, dtype=pd_dtype)
            return string_values.astype(dtype, copy=False)
        else:
>           return np.array(self, dtype=dtype, copy=copy)
E           ValueError: Unable to avoid copy while creating an array as requested.
E           If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
E           For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

../../fireatlas/v3env/lib/python3.11/site-packages/geopandas/array.py:1162: ValueError
```

**Comment by zebbecker** [comment]
The above error is actually internal to geopandas, and does not occur when using geopandas 1.0.0 in combination with numpy 2.0.0... however, we have geopandas <1.0 pinned, and upgrading does break a couple of tests (I think related to a change in parquet I/O syntax) and throws more deprecation warnings. 

So: right now, things run ok with our pinned versions. However, longer term, do we want to upgrade to `geopandas>=1` and `numpy>=2`? And, if so, what needs to happen for us to be comfortable with doing so and unpinning the previous versions? @jsignell @ranchodeluxe

**Comment by jsignell** [comment]
Ok good detective work. Long term we certainly do want to upgrade. I think what would need to happen is just fix any changes and ideally run tests to make sure that the shapes are consistent with expectations.

**Comment by lisamr** [comment]
@zebbecker related to the geopandas version, I wanted to see what happens when geopandas >=1.0 and FEDS worked for me except during some post-processing. 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_70888\2984540271.py in ?()
      5 dl.download_frap()
      6 dl.load_frap()
      7 
      8 # run feds
----> 9 FireRun.constrainByShape_Run(dl.frap_path)
     10 dl.load_feds()
     11 
     12 # # run fofem

c:\Users\lrosenth\OneDrive - California Air Resources Board\Desktop\pyFOFEM\myenv\lib\site-packages\fireatlas\FireRun.py in ?(perimeter_gdf_path, tst, ted, sat, data_source, id_col)
    632     # finally run fire_forward
    633     allfires, allpixels, t_saved = FireMain.Fire_Forward(tst=tst, ted=ted, restart=False, region=region, read_location = 'local', read_saved_location = 'local')
    634 
    635     # Save outputs
--> 636     postprocess.save_individual_fire(allfires.gdf, tst, ted, region)

c:\Users\lrosenth\OneDrive - California Air Resources Board\Desktop\pyFOFEM\myenv\lib\site-packages\fireatlas\utils.py in ?(*args, **kwargs)
     10         # capture the start time
     11         t_start = time()
     12 
     13         # run the function
---> 14         result = f(*args, **kwargs)
     15 
     16         # capture the end time
     17         t_end = time()

c:\Users\lrosenth\OneDrive - California Air Resources Board\Desktop\pyFOFEM\myenv\lib\site-packages\fireatlas\postprocess.py in ?(allfires_gdf, tst, ted, region)
    436     # forward fill any timesteps that are mising
    437     gdf = fill_activefire_rows(gdf, ted)
    438 
    439     # merge any rows that need merging across t
--> 440     data = merge_rows(gdf, fid=region[0])
    441 
    442     # save fire layers - use region name as fid
    443     save_fire_layers(data, region, region[0], tst)

c:\Users\lrosenth\OneDrive - California Air Resources Board\Desktop\pyFOFEM\myenv\lib\site-packages\fireatlas\postprocess.py in ?(allfires_gdf_fid, fid)
    348 def merge_rows(allfires_gdf_fid, fid: int | str):
    349     """For a subset of allfires data containing only one fire, merge any
    350     rows that have the same `t`
    351     """
--> 352     output = allfires_gdf_fid.dissolve(
    353         by="t",
    354         aggfunc={
    355             "meanFRP": lambda x: (

c:\Users\lrosenth\OneDrive - California Air Resources Board\Desktop\pyFOFEM\myenv\lib\site-packages\pandas\core\generic.py in ?(self, name)
   6295             and name not in self._accessors
   6296             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'dissolve'
```

It looks like `fill_activefire_rows` converts the gpd to a pd when it merges with the new rows. It works fine with geopandas 0.14.2, but not with 1.1.0. Just adding another place to look out for when upgrading geopandas. Maybe create a new issue?

**Comment by zebbecker** [comment]
Thanks for the heads up and for documenting it here @lisamr!

**Comment by zebbecker** [comment]
Tested with the following versions and numpy pin is no longer required.

```
SYSTEM INFO
-----------
python     : 3.13.14 | packaged by conda-forge | (main, Jun 12 2026, 09:44:24) [Clang 19.1.7 ]
executable : /opt/homebrew/Caskroom/miniconda/base/envs/fire_env/bin/python
machine    : macOS-15.7.3-arm64-arm-64bit-Mach-O

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.14.1
GEOS lib   : None
GDAL       : 3.12.3
GDAL data dir: /opt/homebrew/Caskroom/miniconda/base/envs/fire_env/share/gdal/
PROJ       : 9.7.1
PROJ data dir: /opt/homebrew/Caskroom/miniconda/base/envs/fire_env/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 1.1.4
numpy      : 2.5.1
pandas     : 3.0.3
pyproj     : 3.7.2
shapely    : 2.1.2
pyogrio    : 0.12.1
geoalchemy2: None
geopy      : None
matplotlib : 3.11.0
mapclassify: 2.10.0
fiona      : 1.10.1
psycopg    : None
psycopg2   : None
pyarrow    : 24.0.0
```
